//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessWorkshop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string IDGender { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int IDGroup { get; set; }
        public Nullable<int> IDWorkShop { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Group Group { get; set; }
        public virtual WorkShop WorkShop { get; set; }
    }
}
